/**
 * SHARED LOGIC — mirrored in
 * `Acheva-WEB-UI/src/app/@features/transcript/export/transcript-pdf.ts`.
 *
 * The two portals share no package, so this is a deliberate copy. A student's
 * transcript and the copy their Course Advisor prints must be the SAME
 * document; if these two files drift, two people holding what they believe is
 * one record are holding two. Change one, change the other.
 *
 * The two copies are NOT byte-identical and cannot be: the repos run Prettier
 * at different print widths, so each is formatted to its own house style. Only
 * the formatting may differ — every value, string and rule here must match.
 */
import {
  ITranscript,
  ITranscriptCourse,
  ITranscriptSession,
  ITranscriptStudent,
  ITranscriptTotals,
} from '../models/transcript.model';

/**
 * Builds the student academic record as a pdfmake document, laid out to match
 * the Registry's printed transcript.
 *
 * pdfmake rather than CSS print, for the same reasons the result sheet uses
 * it: a full academic record runs past one page and needs a header row that
 * repeats, rows that never split across a break, and a footer that stays put.
 * Paged CSS fights all three.
 *
 * Two things are deliberately NOT reproduced from the paper form, and neither
 * is an oversight:
 *
 *  - the `FOR: REGISTRAR` signature line and the `STUDENT'S COPY` stamp.
 *    Acheva does not issue documents on the Registrar's behalf and must not
 *    print the marks of an office it does not hold.
 *  - a computed degree classification. The tables are printed as the form
 *    prints them; which band applies is the Senate's determination at
 *    graduation, and asserting one against a CGPA that is still moving would
 *    state something this system has no standing to state.
 *
 * In their place: the Course Advisor's name as text, and a serial + QR that
 * resolve to the public verifier — settled 2026-08-19, no signature image.
 *
 * The return type is structural rather than pdfmake's own: the library loads
 * lazily, so its types must not be pulled into the eager bundle.
 */
export interface TranscriptDocument {
  content: unknown[];
  [key: string]: unknown;
}

/**
 * The serial and QR printed at the foot of a copy being taken away. Absent on
 * a preview, which mints no serial.
 */
export interface TranscriptProvenance {
  readonly serial: string;
  readonly verifyUrl: string;
  /**
   * A PNG data URI of the QR. Generated by the caller, which owns the lazy
   * `qrcode` import — this module stays free of runtime dependencies.
   */
  readonly qrDataUrl: string;
}

/** Column widths, in points. The title column takes whatever is left. */
const COURSE_WIDTHS = [52, '*', 36, 38, 62, 52];

/** Footnote markers, matched to the notices the server builds. */
const MODERATED_MARK = '†';
const HELD_MARK = '‡';

const BORDER = '#000000';

export function buildTranscriptPdf(
  transcript: ITranscript,
  provenance?: TranscriptProvenance
): TranscriptDocument {
  return {
    pageSize: 'A4',
    pageMargins: [30, 26, 30, 40],
    defaultStyle: { font: 'Roboto', fontSize: 8.5 },

    // A record spanning several years runs to several pages, and a loose page
    // of grades with no name on it is worthless. Every page after the first
    // reintroduces the holder.
    header: (currentPage: number) =>
      currentPage === 1
        ? undefined
        : {
            margin: [30, 14, 30, 0],
            columns: [
              {
                text: transcript.student.fullName.toUpperCase(),
                fontSize: 7.5,
                bold: true,
              },
              {
                text: transcript.student.registrationNumber,
                fontSize: 7.5,
                alignment: 'right',
              },
            ],
          },

    footer: (currentPage: number, pageCount: number) =>
      pageCount > 1
        ? {
            text: `Page ${currentPage} of ${pageCount}`,
            alignment: 'center',
            fontSize: 7,
            color: '#666666',
            margin: [0, 10, 0, 0],
          }
        : undefined,

    content: [
      ...maskHead(transcript),
      studentBlock(transcript.student),
      courseTable(transcript),
      ...(transcript.notices.length > 0 ? [notices(transcript)] : []),
      legends(transcript),
      attribution(transcript, provenance),
    ],

    styles: {
      institution: { fontSize: 13, bold: true, alignment: 'center' },
      officeLine: { fontSize: 9.5, alignment: 'center' },
      addressLine: { fontSize: 9, alignment: 'center' },
      documentTitle: {
        fontSize: 11.5,
        bold: true,
        alignment: 'center',
        margin: [0, 4, 0, 0],
      },
      disclaimer: {
        fontSize: 7.5,
        italics: true,
        alignment: 'center',
        color: '#444444',
        margin: [0, 2, 0, 4],
      },
      fieldLabel: { fontSize: 8, alignment: 'center' },
      fieldValue: { fontSize: 8.5, alignment: 'center' },
      th: { fontSize: 8, bold: true, alignment: 'center' },
      sessionHeading: { fontSize: 8.5, bold: true },
      td: { fontSize: 8.5 },
      tdHeld: { fontSize: 8.5, color: '#666666' },
      totalsRow: { fontSize: 8.5, bold: true, alignment: 'center' },
      sectionLabel: { fontSize: 9, bold: true, alignment: 'center' },
      legendItem: { fontSize: 8 },
      note: { fontSize: 7, color: '#555555' },
    },
  };
}

/**
 * The masthead.
 *
 * The institution, the postal lines and the document title, arranged as the
 * form arranges them — but the Registrar's office is NOT named here. The
 * paper form carries "OFFICE OF THE REGISTRAR / (Records & Statistics Unit)"
 * because the Registrar issues it; this document is issued by the departmental
 * chain through Acheva, and saying otherwise on the masthead would be a claim
 * of authority rather than a matter of layout.
 */
function maskHead(transcript: ITranscript): Record<string, unknown>[] {
  return [
    { text: transcript.institution.toUpperCase(), style: 'institution' },
    { text: 'P.M.B. 1526', style: 'addressLine', margin: [0, 3, 0, 0] },
    { text: 'Owerri Nigeria', style: 'addressLine' },
    { text: "STUDENT'S ACADEMIC RECORD", style: 'documentTitle' },
    {
      text:
        'Issued electronically through Acheva from published departmental ' +
        "results. This is not the Registrar's official transcript.",
      style: 'disclaimer',
    },
  ];
}

/**
 * The Registry's header grid.
 *
 * Built as label/value row PAIRS. A pair whose every value is unrecorded is
 * dropped whole, so a school that has never collected nationality or date of
 * birth gets a tighter block rather than a row of empty boxes; a pair with
 * some values present keeps its grid and leaves the missing cells blank,
 * which on a ruled form reads as "not recorded" rather than as a defect.
 */
function studentBlock(student: ITranscriptStudent): Record<string, unknown> {
  const body: unknown[][] = [];

  // Name and registration number always exist, so this pair never drops.
  body.push(
    labelRow(['Name of Student', 'Sex', 'Date of Birth', 'Reg. No.']),
    valueRow([
      student.fullName.toUpperCase(),
      student.sex ?? '',
      formatLongDate(student.dateOfBirth),
      student.registrationNumber,
    ])
  );

  const origin = [
    student.nationality ?? '',
    student.stateOfOrigin ?? '',
    student.dateOfEntry ?? '',
    student.modeOfEntry ?? '',
  ];
  if (origin.some((value) => value !== '')) {
    body.push(
      labelRow(['Nationality', 'State of Origin', 'Date of Entry', 'Mode of Entry']),
      valueRow(origin.map((value) => value.toUpperCase()))
    );
  }

  // The form pairs School with Department on one line and Option beneath it,
  // rather than giving each its own label row.
  body.push([
    { text: 'School', style: 'fieldLabel' },
    { text: 'Department:', style: 'fieldLabel' },
    {
      text: student.department.toUpperCase(),
      style: 'fieldValue',
      colSpan: 2,
    },
    {},
  ]);
  body.push([
    { text: student.school.toUpperCase(), style: 'fieldValue' },
    { text: 'Option:', style: 'fieldLabel' },
    {
      text: (student.programmeOption ?? '').toUpperCase(),
      style: 'fieldValue',
      colSpan: 2,
    },
    {},
  ]);

  return {
    table: { widths: [195, 72, 120, '*'], body },
    layout: ruledGrid(),
    margin: [0, 0, 0, 0],
  };
}

function labelRow(labels: readonly string[]): unknown[] {
  return labels.map((text) => ({ text, style: 'fieldLabel' }));
}

function valueRow(values: readonly string[]): unknown[] {
  return values.map((text) => ({ text, style: 'fieldValue' }));
}

/**
 * The grades table: one continuous ruled block, session by session.
 *
 * The header row repeats on every page (`headerRows: 1`), because a
 * continuation page of bare numbers under no column titles is unreadable.
 */
function courseTable(transcript: ITranscript): Record<string, unknown> {
  const body: unknown[][] = [
    [
      { text: 'Course\nCode', style: 'th' },
      { text: 'Title of Course', style: 'th' },
      { text: 'Units', style: 'th' },
      { text: 'Grade', style: 'th' },
      { text: 'Total Grade\nPoints', style: 'th' },
      { text: 'Cum\nG.P.A.', style: 'th' },
    ],
  ];

  const multiSession = transcript.sessions.length > 1;

  for (const session of transcript.sessions) {
    // The carry-forward line the paper form opens a continuation page with:
    // "2017/2018 | 41 | 169". Only ever on the first session of a document
    // that already has history behind it — which, since Acheva prints the
    // whole record in one file, is never. Kept because the server can hand
    // back a partial record and the line must be right if it does.
    if (session.broughtForward) {
      body.push(carryForwardRow(session));
    }

    for (const semester of session.semesters) {
      body.push(headingRow(semester.heading));

      for (const course of semester.courses) {
        body.push(courseRow(course));
      }
    }

    // A per-session running total, so a multi-year record shows where the
    // CGPA stood at the close of each year rather than only at the end.
    if (multiSession) {
      body.push(subtotalRow(`TOTAL AS AT ${session.session}`, session.cumulative));
    }

    body.push(spacerRow());
  }

  // The figures the whole document exists to state.
  body.push(grandTotalRow(transcript.cumulative));

  return {
    table: {
      headerRows: 1,
      dontBreakRows: true,
      widths: COURSE_WIDTHS,
      body,
    },
    layout: ruledGrid(),
    margin: [0, 0, 0, 0],
  };
}

function carryForwardRow(session: ITranscriptSession): unknown[] {
  const brought = session.broughtForward as ITranscriptTotals;
  return [
    { text: '', style: 'td' },
    { text: `Brought forward`, style: 'sessionHeading' },
    { text: String(brought.units), style: 'totalsRow' },
    { text: '', style: 'td' },
    { text: String(brought.gradePoints), style: 'totalsRow' },
    { text: '', style: 'td' },
  ];
}

function headingRow(heading: string): unknown[] {
  return [
    { text: '', style: 'td' },
    { text: heading, style: 'sessionHeading', colSpan: 5 },
    {},
    {},
    {},
    {},
  ];
}

/**
 * One course.
 *
 * A row that does not count prints its grade — the student sat the course and
 * the mark is real — but leaves Total Grade Points BLANK rather than showing
 * 0, because 0 in that column is what an F earns and would read as a failure.
 * The marker beside the title sends the reader to the note explaining why.
 */
function courseRow(course: ITranscriptCourse): unknown[] {
  const marks = [course.moderated ? MODERATED_MARK : '', course.counted ? '' : HELD_MARK].join('');

  const style = course.counted ? 'td' : 'tdHeld';

  return [
    { text: course.code, style },
    { text: `${course.title}${marks ? ` ${marks}` : ''}`, style },
    {
      text: course.units === null ? '' : String(course.units),
      style,
      alignment: 'center',
    },
    { text: course.grade ?? '', style, alignment: 'center' },
    {
      text: course.gradePoints === null ? '' : String(course.gradePoints),
      style,
      alignment: 'center',
    },
    { text: '', style },
  ];
}

function subtotalRow(label: string, totals: ITranscriptTotals): unknown[] {
  return [
    { text: '', style: 'td' },
    { text: label, style: 'sessionHeading', alignment: 'right' },
    { text: String(totals.units), style: 'totalsRow' },
    { text: '', style: 'td' },
    { text: String(totals.gradePoints), style: 'totalsRow' },
    { text: totals.gpa.toFixed(2), style: 'totalsRow' },
  ];
}

/** A blank band between sessions, as the paper form leaves. */
function spacerRow(): unknown[] {
  return Array.from({ length: 6 }, () => ({ text: ' ', style: 'td' }));
}

function grandTotalRow(totals: ITranscriptTotals): unknown[] {
  return [
    { text: '', style: 'totalsRow' },
    { text: '', style: 'totalsRow' },
    { text: String(totals.units), style: 'totalsRow' },
    { text: '', style: 'totalsRow' },
    { text: String(totals.gradePoints), style: 'totalsRow' },
    { text: totals.gpa.toFixed(2), style: 'totalsRow' },
  ];
}

/** The notes the server decided this particular record needs. */
function notices(transcript: ITranscript): Record<string, unknown> {
  return {
    margin: [0, 6, 0, 0],
    stack: transcript.notices.map((note) => ({
      text: note,
      style: 'note',
      margin: [0, 0.5],
    })),
  };
}

/**
 * The two legends the form prints at the foot, kept together so neither is
 * orphaned onto a page of its own.
 */
function legends(transcript: ITranscript): Record<string, unknown> {
  return {
    unbreakable: true,
    margin: [0, 8, 0, 0],
    stack: [gradingSystem(transcript), classification(transcript)],
  };
}

/**
 * "A - Excellent: 5 points", in the two columns the form uses.
 *
 * Built from the scale the server sends, which is derived from the same table
 * that awards the grades — so the legend cannot drift from the grades printed
 * above it on the same page.
 */
function gradingSystem(transcript: ITranscript): Record<string, unknown> {
  const items = transcript.gradingScale.map(
    (band) =>
      `${band.grade} - ${band.description}: ${band.points} ${
        band.points === 1 ? 'point' : 'points'
      }`
  );
  const half = Math.ceil(items.length / 2);

  return {
    stack: [
      { text: 'GRADING SYSTEM', style: 'sectionLabel', margin: [0, 0, 0, 4] },
      {
        columns: [
          { stack: items.slice(0, half).map(legendLine) },
          { stack: items.slice(half).map(legendLine) },
        ],
      },
      {
        text: 'I - Incomplete    W - Withdrew    WP - Withdrew Passing    WF - Withdrew Failing',
        style: 'legendItem',
        alignment: 'center',
        margin: [0, 3, 0, 0],
      },
    ],
  };
}

/**
 * Both classification tables, as the form carries them.
 *
 * No class is asserted for this student — see the note at the top of the file.
 */
function classification(transcript: ITranscript): Record<string, unknown> {
  return {
    margin: [0, 7, 0, 0],
    stack: transcript.classificationScales.map((scale) => {
      const items = scale.bands.map(
        (band) => `${band.label}: ${band.min.toFixed(2)} - ${band.max.toFixed(2)}`
      );
      const half = Math.ceil(items.length / 2);

      return {
        margin: [0, 0, 0, 4],
        stack: [
          {
            text: `DEGREE CLASSIFICATION - (${scale.era})`,
            style: 'sectionLabel',
            margin: [0, 0, 0, 3],
          },
          {
            columns: [
              { stack: items.slice(0, half).map(legendLine) },
              { stack: items.slice(half).map(legendLine) },
            ],
          },
        ],
      };
    }),
  };
}

function legendLine(text: string): Record<string, unknown> {
  return { text, style: 'legendItem', margin: [0, 0.3] };
}

/**
 * What replaces the signature block.
 *
 * The paper form ends in a Registrar's signature over a ruled line. This
 * document cannot and must not imitate that, so it ends in the two things
 * that actually make it checkable: the Course Advisor named in text, and a
 * serial plus QR resolving to the public verifier.
 *
 * The wording tells the reader what to DO — open the address, then compare
 * what it shows against the paper in hand — because proving only that "a
 * document with this serial was issued" would not catch an altered grade.
 */
function attribution(
  transcript: ITranscript,
  provenance?: TranscriptProvenance
): Record<string, unknown> {
  const advisorLine = transcript.courseAdvisor
    ? [
        { text: 'COURSE ADVISOR', fontSize: 7.5, bold: true },
        {
          text: transcript.courseAdvisor.toUpperCase(),
          fontSize: 8.5,
          margin: [0, 1, 0, 0],
        },
      ]
    : [];

  if (!provenance) {
    return {
      unbreakable: true,
      margin: [0, 8, 0, 0],
      stack: [
        ...advisorLine,
        {
          text:
            `Generated from Acheva on ${formatShortDate(transcript.generatedAt)}. ` +
            'Preview only — a serial is issued when the document is downloaded.',
          fontSize: 7,
          color: '#777777',
          margin: [0, 6, 0, 0],
        },
      ],
    };
  }

  return {
    unbreakable: true,
    margin: [0, 8, 0, 0],
    columns: [
      { image: provenance.qrDataUrl, width: 56, height: 56 },
      {
        width: '*',
        margin: [10, 2, 0, 0],
        stack: [
          ...advisorLine,
          {
            text: 'VERIFY THIS DOCUMENT',
            fontSize: 8,
            bold: true,
            margin: [0, advisorLine.length > 0 ? 6 : 0, 0, 0],
          },
          {
            text: provenance.serial,
            fontSize: 11,
            bold: true,
            characterSpacing: 1,
            margin: [0, 2, 0, 2],
          },
          {
            text:
              `Scan the code, or enter the serial at ${verifyHost(provenance.verifyUrl)}. ` +
              'Check that what it shows matches this document — an altered ' +
              'copy will not match.',
            fontSize: 7,
            color: '#444444',
          },
          {
            text:
              `Issued from Acheva on ${formatShortDate(transcript.generatedAt)}. ` +
              'Compiled from results published through the departmental ' +
              'approval chain.',
            fontSize: 6.5,
            color: '#777777',
            margin: [0, 2, 0, 0],
          },
        ],
      },
    ],
  };
}

/** The ruled box the whole form is drawn in. */
function ruledGrid(): Record<string, unknown> {
  return {
    hLineWidth: () => 0.5,
    vLineWidth: () => 0.5,
    hLineColor: () => BORDER,
    vLineColor: () => BORDER,
    paddingTop: () => 2.5,
    paddingBottom: () => 2.5,
    paddingLeft: () => 4,
    paddingRight: () => 4,
  };
}

/** `verify.acheva.app` from the full URL — shorter to read off paper. */
function verifyHost(verifyUrl: string): string {
  try {
    return new URL(verifyUrl).host;
  } catch {
    return verifyUrl;
  }
}

/** "December 4, 2001" — the long form the transcript's DOB field uses. */
export function formatLongDate(iso: string | null): string {
  if (!iso) return '';
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

/** dd/mm/yyyy — matches the result sheet's date format. */
export function formatShortDate(iso: string | null): string {
  if (!iso) return '';
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '';
  const dd = String(date.getDate()).padStart(2, '0');
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  return `${dd}/${mm}/${date.getFullYear()}`;
}

/** The download filename: `20171064153_Academic_Record.pdf`. */
export function transcriptFileName(transcript: ITranscript): string {
  const reg = transcript.student.registrationNumber.replace(/\s+/g, '') || 'transcript';
  return `${reg}_Academic_Record`;
}
